name: jaguar_cqrs
description: Command Query Responsibility Separation (CQRS) and Event sourcing framework for Dart.
version: 2.1.5
homepage: https://github.com/Jaguar-dart/cqrs
authors:
  - Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: ^1.3.0
